version: 2
project_name: twig

before:
  hooks:
    - go mod download

builds:
  - id: twig
    ldflags:
      - -s -w -X github.com/dwadp/twig/cmd/twig.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64

release:
  github:
    owner: dwadp
    name: twig
  prerelease: auto
  name_template: "{{ .Version }}"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
